"""add trading lifecycle

Revision ID: 99458cd8c635
Revises: 20260903_0002
Create Date: 2026-09-03 23:59:51.411387
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "99458cd8c635"
down_revision: str | None = "20260903_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_snapshots",
        sa.Column("equity", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("cash", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("buying_power", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("options_buying_power", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("options_exposure", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("daily_pnl", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_pnl", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_observed_at"),
        "portfolio_snapshots",
        ["observed_at"],
        unique=False,
    )
    op.create_table(
        "positions",
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        sa.Column("contract_symbol", sa.String(length=64), nullable=False),
        sa.Column("underlying_symbol", sa.String(length=15), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("exit_reason", sa.String(length=32), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index(op.f("ix_positions_candidate_id"), "positions", ["candidate_id"], unique=False)
    op.create_index(
        op.f("ix_positions_contract_symbol"), "positions", ["contract_symbol"], unique=False
    )
    op.create_index(
        op.f("ix_positions_underlying_symbol"), "positions", ["underlying_symbol"], unique=False
    )
    op.create_table(
        "trade_candidates",
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=15), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("signal_score", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_candidates")),
        sa.UniqueConstraint("correlation_id", name=op.f("uq_trade_candidates_correlation_id")),
    )
    op.create_index(
        op.f("ix_trade_candidates_symbol"), "trade_candidates", ["symbol"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_positions_candidate_id_trade_candidates"),
        "positions",
        "trade_candidates",
        ["candidate_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "option_contract_snapshots",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("contract_symbol", sa.String(length=64), nullable=False),
        sa.Column("underlying_symbol", sa.String(length=15), nullable=False),
        sa.Column("option_type", sa.String(length=8), nullable=False),
        sa.Column("strike_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("bid", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("ask", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("midpoint", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("spread_percentage", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("premium", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.JSON(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["trade_candidates.id"],
            name=op.f("fk_option_contract_snapshots_candidate_id_trade_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_option_contract_snapshots")),
    )
    op.create_index(
        op.f("ix_option_contract_snapshots_candidate_id"),
        "option_contract_snapshots",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("client_order_id", sa.String(length=48), nullable=False),
        sa.Column("provider_order_id", sa.Uuid(), nullable=True),
        sa.Column("provider_request_id", sa.String(length=128), nullable=True),
        sa.Column("contract_symbol", sa.String(length=64), nullable=False),
        sa.Column("underlying_symbol", sa.String(length=15), nullable=False),
        sa.Column("intent", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("average_fill_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("maximum_loss", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["trade_candidates.id"],
            name=op.f("fk_orders_candidate_id_trade_candidates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("client_order_id", name="uq_orders_client_order_id"),
        sa.UniqueConstraint("provider_order_id", name=op.f("uq_orders_provider_order_id")),
    )
    op.create_index(op.f("ix_orders_candidate_id"), "orders", ["candidate_id"], unique=False)
    op.create_table(
        "position_snapshots",
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_position_snapshots_position_id_positions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_snapshots")),
    )
    op.create_index(
        op.f("ix_position_snapshots_position_id"),
        "position_snapshots",
        ["position_id"],
        unique=False,
    )
    op.create_table(
        "risk_decisions",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("evaluations", sa.JSON(), nullable=False),
        sa.Column("approved_quantity", sa.Integer(), nullable=False),
        sa.Column("maximum_capital", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["trade_candidates.id"],
            name=op.f("fk_risk_decisions_candidate_id_trade_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
    )
    op.create_index(
        op.f("ix_risk_decisions_candidate_id"), "risk_decisions", ["candidate_id"], unique=False
    )
    op.create_table(
        "fills",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("provider_fill_id", sa.String(length=128), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
        sa.UniqueConstraint("provider_fill_id", name=op.f("uq_fills_provider_fill_id")),
    )
    op.create_index(op.f("ix_fills_order_id"), "fills", ["order_id"], unique=False)
    op.add_column("ai_decisions", sa.Column("candidate_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_ai_decisions_candidate_id"), "ai_decisions", ["candidate_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_ai_decisions_candidate_id_trade_candidates"),
        "ai_decisions",
        "trade_candidates",
        ["candidate_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("journal_events", sa.Column("candidate_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_journal_events_candidate_id"), "journal_events", ["candidate_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_journal_events_candidate_id_trade_candidates"),
        "journal_events",
        "trade_candidates",
        ["candidate_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_journal_events_candidate_id_trade_candidates"),
        "journal_events",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_journal_events_candidate_id"), table_name="journal_events")
    op.drop_column("journal_events", "candidate_id")
    op.drop_constraint(
        op.f("fk_ai_decisions_candidate_id_trade_candidates"), "ai_decisions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_ai_decisions_candidate_id"), table_name="ai_decisions")
    op.drop_column("ai_decisions", "candidate_id")
    op.drop_index(op.f("ix_fills_order_id"), table_name="fills")
    op.drop_table("fills")
    op.drop_index(op.f("ix_risk_decisions_candidate_id"), table_name="risk_decisions")
    op.drop_table("risk_decisions")
    op.drop_index(op.f("ix_position_snapshots_position_id"), table_name="position_snapshots")
    op.drop_table("position_snapshots")
    op.drop_index(op.f("ix_orders_candidate_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(
        op.f("ix_option_contract_snapshots_candidate_id"), table_name="option_contract_snapshots"
    )
    op.drop_table("option_contract_snapshots")
    op.drop_constraint(
        op.f("fk_positions_candidate_id_trade_candidates"), "positions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_trade_candidates_symbol"), table_name="trade_candidates")
    op.drop_table("trade_candidates")
    op.drop_index(op.f("ix_positions_underlying_symbol"), table_name="positions")
    op.drop_index(op.f("ix_positions_contract_symbol"), table_name="positions")
    op.drop_index(op.f("ix_positions_candidate_id"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_portfolio_snapshots_observed_at"), table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    # ### end Alembic commands ###
